### PR TITLE
Add README and small fixes

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ColinMaudry** [comment]
Wow merci @ericgaspar 🥇

**Comment by ColinMaudry** [comment]
!testme

**Comment by ColinMaudry** [comment]
!testme

**Comment by ericgaspar** [comment]
Why do you use cURL? Not sure about the benefit of using cUrl to install the source jar file instead of ynh_setup_source ...

**Comment by ColinMaudry** [comment]
The installation [failed](https://ci-apps-dev.yunohost.org/ci/job/636) and I thought ynh_setup_source was for zip/tar. I'll roll it back.

**Comment by ericgaspar** [comment]
The jar file is correctly installed. After installing the app, I get a 502 error... maybe an issue with Metabase config file... IDK

**Pull request merged**
